name: art_gallery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  chopper: ^5.1.0
  json_annotation: ^4.5.0
  provider: ^6.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  logger: ^1.1.0
  stream_transform: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  chopper_generator: ^5.1.0+1
  json_serializable: ^6.2.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/image_placeholder.jpg
