name: Gate

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - run: flutter --version

      - name: Flutter analyze
        run: flutter analyze

      - name: Dart code analyze
        run: dart analyze

      - name: Run tests
        run: flutter test
